# Generated by Django 2.1 on 2018-08-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memsy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mems',
            name='mem',
            field=models.ImageField(blank=True, default='pictures/no-image.jpg', upload_to='pictures'),
        ),
    ]
