# Generated by Django 2.1 on 2018-08-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memsy', '0002_mems_mem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mems',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
