# Generated by Django 2.1 on 2018-08-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memsy', '0004_auto_20180827_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mems',
            name='mem',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
