# Generated by Django 2.1 on 2018-08-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memsy', '0005_auto_20180827_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mems',
            name='mem',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
