# Generated by Django 2.1 on 2018-08-28 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memsy', '0006_auto_20180827_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mems',
            name='likes',
        ),
        migrations.AddField(
            model_name='mems',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
