# Generated by Django 2.1 on 2018-08-30 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memsy', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 8, 30, 11, 1, 11, 798244, tzinfo=utc)),
        ),
    ]
