# Generated by Django 2.1 on 2018-08-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memsy', '0012_auto_20180830_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
    ]
